name: Health Check

on:
  schedule:
    - cron: "0 * * * *"
  push:

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Service Health
        uses: Jtalk/url-health-check-action@v3
        with:
          url: "https://full-stack-open-pokedex-jzhz.onrender.com/health"
          max-attempts: 3
          retry-delay: 5s
          follow-redirect: true
